version: '3.4'
services:
  sentinel1:
    image: redis:4-alpine
    container_name: redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel1.conf
    network_mode: "host"
    ports:
      - 26379:26379
    volumes:
      - ./conf/sentinel1.conf:/usr/local/etc/redis/sentinel1.conf
#      - ./data/sentinel1:/data

  sentinel2:
    image: redis:4-alpine
    container_name: redis-sentinel-2
    command: redis-sentinel /usr/local/etc/redis/sentinel2.conf
    ports:
      - 26380:26379
    network_mode: "host"
    volumes:
      - ./conf/sentinel2.conf:/usr/local/etc/redis/sentinel2.conf
#      - ./data/sentinel2:/data

  sentinel3:
    image: redis:4-alpine
    container_name: redis-sentinel-3
    command: redis-sentinel /usr/local/etc/redis/sentinel3.conf
    network_mode: "host"
    ports:
      - 26381:26379
    volumes:
      - ./conf/sentinel3.conf:/usr/local/etc/redis/sentinel3.conf
#      - ./data/sentinel3:/data